version: '3'

services:
  angular-app:
    build: .
    container_name: angular-app
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    ports:
      - 4201:4200

volumes:
  node_modules:
